### ISSUE TITLE
incompatible with dragonapi and endlessids

### ISSUE THREAD

**Issue by Universal118** [LegacyModdingMC/UniMixins#2]
[fml-client-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/10716682/fml-client-latest.log)

**Comment by makamys** [comment]
I'm not sure if UniMixins is related to this. Does it happen if you replace it with GasStation (and remove all the mods that need GTNHMixins)?

**Comment by makamys** [comment]
I found the issue. It happens because you renamed your DragonAPI jar to `@DragonAPI+1.7.10+V31b.jar`. This makes EndlessIDs fail to detect it and apply compatibility tweaks, since [it checks if the jar starts with "dragonapi"](https://github.com/FalsePattern/EndlessIDs/blob/7381139fdf2ed9a96f4e59d4c833ec25dd4a1aae/src/main/java/com/falsepattern/endlessids/mixin/plugin/TargetedMod.java#L26). Either way, UniMixins is not related (the same crash happens if GasStation is used).

**Comment by Universal118** [comment]
thank you
