### ISSUE TITLE
Unimixin crash the game when modernkeybinding + bugtorch is installed (its work with spongemixin)

### ISSUE THREAD

**Issue by quentin452** [LegacyModdingMC/UniMixins#8]
[latest.log](https://github.com/LegacyModdingMC/UniMixins/files/10954396/latest.log)

[crash-2023-03-13_07.56.54-client.txt](https://github.com/LegacyModdingMC/UniMixins/files/10954400/crash-2023-03-13_07.56.54-client.txt)

**Comment by makamys** [comment]
I can reproduce this if I enable `fasterOptionLoading` in BugTorch's config.

The reason you don't get a crash with SpongeMixins is because BugTorch requires GTNHMixins, so, since you're missing GTNHMixins, BugTorch doesn't load properly. If I add GTNHMixins, the same issue happens, so this isn't an UniMixins bug.

The actual issue here is that BugTorch's `fasterOptionLoading` is incompatible with ModernKeyBinding (BugTorch overwrites `GameSettings#loadOptions`, while MKB injects into it). I recommend just disabling the option.

**Comment by quentin452** [comment]
ok thx
